service: kanban-user-microservice

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1

functions:
    userService:
        handler: index.handler
        events:
            - http:
                  path: users
                  method: get

plugins:
    - serverless-offline